---
name: CI

# One CI to rule them all,
# one CI to find them,
# One CI to bring them all
# and in the flakyness bind them.

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

env:
  DEBIAN_FRONTEND: noninteractive

  # Note: ca-certificates and git are needed for actions/checkout to use git
  # which is needed for codecov/codecov-action.
  checkout_deps: ca-certificates git
  base_deps: >
    python3 python3-apt python3-psutil python3-pytest python3-pytest-cov
  build_deps: >
    default-jdk-headless pkg-config python3-distutils-extra python3-setuptools
  common_deps: python3-distro-info python3-launchpadlib
  gtk_deps: gir1.2-gtk-3.0 gir1.2-wnck-3.0 gnome-icon-theme procps python3-gi
  kde_deps: procps pyqt6-dev-tools python3-pyqt6
  unit_deps: locales python3-systemd python3-zstandard
  integration_deps: >
    bash binutils gcc gdb kmod libc6-dev libglib2.0-dev libxml2-utils
    polkitd python3-systemd valgrind xterm
  system_deps: >
    dbus dbus-x11 gdb-multiarch gvfs-daemons psmisc python3-dbus
    ubuntu-dbgsym-keyring ubuntu-keyring xterm xvfb
  system_internet_deps: >
    chaos-marmosets dpkg-dev gdb-multiarch ubuntu-dbgsym-keyring ubuntu-keyring
    valgrind

jobs:
  system-internet-installed:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
    steps:
      - name: Remove system installed Apport
        run: >
          sudo apt-get remove --purge --yes
          apport python3-apport python3-problem-report
      - name: Enable 'deb-src' URIs in /etc/apt/sources.list.d/ubuntu.sources
        run: >
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/'
          /etc/apt/sources.list.d/ubuntu.sources
      - name: Install dependencies
        run: >
          sudo apt-get update
          && sudo apt-get install --no-install-recommends --yes
          $base_deps $build_deps $common_deps $gtk_deps $system_internet_deps
      - uses: actions/checkout@v6
      - name: Install
        run: >
          sudo python3 -m coverage run
          ./setup.py install --install-layout=deb --prefix=/usr --root=/
          && sudo chown "$SUDO_UID:$SUDO_GID" .coverage
          && python3 -m coverage xml -o coverage-setup.xml
      - name: Cleanup /var/crash/
        run: sudo rm -f /var/crash/*.crash
      - name: Enable Apport
        run: sudo /usr/share/apport/apport --start
      - name: Run system tests that require Internet access
        env:
          GDK_BACKEND: x11
        run: >
          WORKDIR=$(mktemp -d -t apport.XXXXXXXXXX)
          && cp -r tests pyproject.toml "$WORKDIR"
          && cd "$WORKDIR"
          && sudo xvfb-run python3 -m pytest -v -ra --cov=$(pwd)
          --cov-report=xml --durations=0 -m "requires_internet" tests/system/
          && cd -
          && cp "$WORKDIR/coverage.xml" .
      - name: Upload coverage
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ github.job }}
          path: ./coverage*.xml
